# Generated by Django 4.2.15 on 2024-08-14 07:19

import accounts.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='national_code',
            field=models.CharField(max_length=10, null=True, validators=[accounts.validators.validate_national_code]),
        ),
    ]
